language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: true

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction
  - travis_retry composer require php-coveralls/php-coveralls

script:
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS

after_script:
  - bash <(curl -s https://codecov.io/bash)
  - export CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
  - export CI_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
  - export CI_BRANCH="$TRAVIS_BRANCH"
  - travis_retry php vendor/bin/php-coveralls -v --coverage_clover clover.xml --json_path coveralls-upload.json
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      cd ../../..
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
